name: Node.js Package

on:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "main"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install dependencies
        working-directory: garage-management-ui
        run: npm ci
      # - run: npm test

  publish-gpr:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: write # Cần để push lên GitHub Pages
      packages: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Lấy đầy đủ history để deploy gh-pages

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: https://npm.pkg.github.com/

      - name: Setup Git
        run: |
          git config --global user.email "github-actions-bot@github.com"
          git config --global user.name "github-actions[bot]"
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git

      - name: Install dependencies & Build
        working-directory: garage-management-ui
        run: |
          npm ci
          npm run build --if-present

      - name: Deploy to GitHub Pages
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }} # Dùng GH_PAT thay vì GITHUB_TOKEN nếu cần
        working-directory: garage-management-ui
        run: npm run deploy
